### ISSUE TITLE
Control isn't resized correctly

### ISSUE THREAD

**Issue by Logix-Dev** [varon/GLWpfControl#33]
Hi, first of all, thanks for this very useful package, it solves some current issues with OpenTK and its dependencies and is very nice to use.

However, the control displays odd behaviour when it's resized. If put inside a `Grid`, and the `Grid` _column_ is resized using a `GridSplitter`, the control will not update its size until the _row_ is resized... and vice versa. Note: The parent control type seems to be irrelevant, this happens when parenting the `GLWpfControl` inside other container types, too.

Here's a screen recording (in GIF format) which shows the undesirable behaviour:
https://i.gyazo.com/972ae86b2ff91b09da3fa715075c2302.gif

I'm not sure if this is intentional behaviour, or can be solved via code (perhaps by invalidating something?), but it seems a little strange to me, and I'd probably consider it a bug... unless it's just the way I'm using the control

**Comment by Simi4** [comment]
This bug should fixed by #27

**Comment by varon** [comment]
Leaving this open, as despite the fix, it looks like this can still happen in some very edge cases with a ton of nested controls. Also seeing the width-only resize issues.

**Comment by NogginBops** [comment]
Moving this to the next release.
If this issue doesn't have any updates or people experiencing the issue I might close it next version.

**Comment by NogginBops** [comment]
There have been no more reports of this for the last 4 years. If we get any new reports we can open a new issues for that. Closing this.
